{% set name = "azure-mgmt-eventgrid" %}
{% set version = "10.4.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 303e5e27cf4bb5ec833ba4e5a9ef70b5bc410e190412ec47cde59d82e413fb7e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python
    - azure-common >=1.1,<2
    - azure-mgmt-core >=1.3.0,<2.0.0
    - isodate >=0.6.1
    - typing_extensions >=4.6.0

# Azure sdk test tools are not supported by pypi and Anaconda.
# Only pip check is performed.
test:
  source_files:
    - tests
  imports:
    - azure.mgmt.eventgrid
    - azure.mgmt.eventgrid.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Event Grid Management Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    This is the Microsoft Azure Event Grid Management Client Library.
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
